# Data Analysis Course
## using Python

In [1]:
print("Welcome to Python")

Welcome to Python


[Our Website](https://www.abadnet.com.sa)

![Logo](https://cdn.dribbble.com/users/10882/screenshots/15172621/media/cd2246d5d0f54f9a4316bd4d276764b2.png?compress=1&resize=400x300)

### Topics:
   - Python Revision
   - Data **Cleaning**
   - Data *Visualization*
   - Models
   
> This is a quote
> 
> more text

## Lists

In [2]:
marks = [23, 18, 12, 25]

In [3]:
marks

[23, 18, 12, 25]

In [4]:
marks[0]

23

In [5]:
marks[-1]

25

In [6]:
len(marks)

4

In [7]:
marks.append(17)
marks

[23, 18, 12, 25, 17]

In [8]:
marks.insert(0, 20)
marks

[20, 23, 18, 12, 25, 17]

In [9]:
marks_g2 = [18, 25, 23, 14]
marks.extend(marks_g2)
marks

[20, 23, 18, 12, 25, 17, 18, 25, 23, 14]

In [10]:
marks += marks_g2
marks

[20, 23, 18, 12, 25, 17, 18, 25, 23, 14, 18, 25, 23, 14]

In [11]:
marks.remove(14)
marks

[20, 23, 18, 12, 25, 17, 18, 25, 23, 18, 25, 23, 14]

In [12]:
marks.pop(5)
marks

[20, 23, 18, 12, 25, 18, 25, 23, 18, 25, 23, 14]

In [13]:
marks.sort(reverse=True)
marks

[25, 25, 25, 23, 23, 23, 20, 18, 18, 18, 14, 12]

In [14]:
marks = list(set(marks))
marks

[12, 14, 18, 20, 23, 25]

In [15]:
# marks[0]

In [16]:
marks.sort(reverse=True)
marks

[25, 23, 20, 18, 14, 12]

In [17]:
marks[0:3]

[25, 23, 20]

In [18]:
marks[:3]

[25, 23, 20]

In [19]:
marks[-3:]

[18, 14, 12]

In [20]:
del marks[-1]

In [21]:
marks

[25, 23, 20, 18, 14]

In [22]:
13 in marks

False

## Tuple:

In [23]:
days = ("Sunday", "Monday", "Tuesday", "Wednesday")
days

('Sunday', 'Monday', 'Tuesday', 'Wednesday')

In [24]:
days[0]

'Sunday'

In [25]:
days[-1]

'Wednesday'

In [26]:
len(days)

4

In [27]:
# days[0] = "Sun"  -- Will not work because tuple is immutable

In [28]:
list(days)

['Sunday', 'Monday', 'Tuesday', 'Wednesday']

## Dict:

In [29]:
countries = {
    "sa": "Saudi Arabia",
    "ae": "Arab Emirates",
    "eg": "Egypt"
}

In [30]:
# countries["ae"]
countries.get("ae", "Not Found")

'Arab Emirates'

In [31]:
countries

{'sa': 'Saudi Arabia', 'ae': 'Arab Emirates', 'eg': 'Egypt'}

In [32]:
list(countries.values())

['Saudi Arabia', 'Arab Emirates', 'Egypt']

In [33]:
list(countries.keys())

['sa', 'ae', 'eg']

In [34]:
items = list(countries.items())
items

[('sa', 'Saudi Arabia'), ('ae', 'Arab Emirates'), ('eg', 'Egypt')]

In [35]:
items[0][1]

'Saudi Arabia'

In [36]:
# countries["eg"] = "Republic of Egypt"
countries.update({"eg": "Republic of Egypt"})
countries

{'sa': 'Saudi Arabia', 'ae': 'Arab Emirates', 'eg': 'Republic of Egypt'}

In [37]:
# countries["pl"] = "Palstine"
countries.update({"pl": "Palstine"})
countries

{'sa': 'Saudi Arabia',
 'ae': 'Arab Emirates',
 'eg': 'Republic of Egypt',
 'pl': 'Palstine'}

In [38]:
# del countries["ae"]
countries.pop("ae")
countries

{'sa': 'Saudi Arabia', 'eg': 'Republic of Egypt', 'pl': 'Palstine'}

In [39]:
len(countries)

3

In [40]:
"ae" in countries

False

In [41]:
list(countries)

['sa', 'eg', 'pl']

In [42]:
list("Welcome")

['W', 'e', 'l', 'c', 'o', 'm', 'e']

## Loops:

for `new_var` in `iterable`:

    >
    >
    
--
--
    

In [43]:
for m in marks:
    print(m + 2)
    print("-" * 20)

print("*" * 20)

27
--------------------
25
--------------------
22
--------------------
20
--------------------
16
--------------------
********************


In [44]:
message = "Hello"
for c in message:
    print(c)
    

H
e
l
l
o


In [45]:
mobile = "0599888921"
for d in mobile:
    if not d.isdigit():
        print("Not a valid mobile")
        break


In [46]:
mobile.isdigit()

True

In [47]:
list(range(1, 10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [48]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [49]:
list(range(1, 10, 2))

[1, 3, 5, 7, 9]

In [50]:
for i in range(10):
    print(i * "-")
#     print("Hello world")



-
--
---
----
-----
------
-------
--------
---------


while `bool-expr`:
    
    --
    --
    
 --

In [51]:
x = 1
while x <= 10:
    print(x)
    x += 1


1
2
3
4
5
6
7
8
9
10


In [52]:
for y in range(1, 11):
    print(y)

1
2
3
4
5
6
7
8
9
10


In [53]:
countries

{'sa': 'Saudi Arabia', 'eg': 'Republic of Egypt', 'pl': 'Palstine'}

In [54]:
for k, v in countries.items():
    print(k, "=>", v)

sa => Saudi Arabia
eg => Republic of Egypt
pl => Palstine


## List & Dict Comprehension

In [55]:
for i in range(len(marks)):
    marks[i] += 2
    
marks

[27, 25, 22, 20, 16]

In [56]:
new_marks = []
for m in marks:
    new_marks.append(m + 2)
    
new_marks

[29, 27, 24, 22, 18]

In [57]:
marks

[27, 25, 22, 20, 16]

In [58]:
new_marks = [m + 5 for m in marks]
new_marks

[32, 30, 27, 25, 21]

In [59]:

teas = ['earl grey', 'darjeeling', 'english breakfast', 'lapsang souchong', 
        'oolong', 'kombucha', 'green tea']

teas = [t.upper() for t in teas]
teas

['EARL GREY',
 'DARJEELING',
 'ENGLISH BREAKFAST',
 'LAPSANG SOUCHONG',
 'OOLONG',
 'KOMBUCHA',
 'GREEN TEA']

In [60]:
text = "Hello"
text.count("e")

1

In [61]:
lengths = [len(t) for t in teas]
lengths

[9, 10, 17, 16, 6, 8, 9]

In [62]:
countries = ["Saudi Arabia", "Arab Emirates", "Egypt"]
countries_d = {c[0]: c for c in countries}
countries_d

{'S': 'Saudi Arabia', 'A': 'Arab Emirates', 'E': 'Egypt'}

In [63]:
lengths = {t: len(t) for t in teas}
lengths

{'EARL GREY': 9,
 'DARJEELING': 10,
 'ENGLISH BREAKFAST': 17,
 'LAPSANG SOUCHONG': 16,
 'OOLONG': 6,
 'KOMBUCHA': 8,
 'GREEN TEA': 9}

In [64]:
lengths = {t: [len(t), t.count(" ") + 1] for t in teas}
lengths

{'EARL GREY': [9, 2],
 'DARJEELING': [10, 1],
 'ENGLISH BREAKFAST': [17, 2],
 'LAPSANG SOUCHONG': [16, 2],
 'OOLONG': [6, 1],
 'KOMBUCHA': [8, 1],
 'GREEN TEA': [9, 2]}

In [65]:
lengths = {t: (len(t), t.count(" ") + 1) for t in teas}
lengths

{'EARL GREY': (9, 2),
 'DARJEELING': (10, 1),
 'ENGLISH BREAKFAST': (17, 2),
 'LAPSANG SOUCHONG': (16, 2),
 'OOLONG': (6, 1),
 'KOMBUCHA': (8, 1),
 'GREEN TEA': (9, 2)}

In [66]:
print(lengths["EARL GREY"][1])

2


In [67]:
print(lengths["EARL GREY"])

(9, 2)


In [68]:
surnames = ['grant','Sketchley','REUSTLE','huse','Mellgard']

result = {n.upper(): len(n) for n in surnames}
result

{'GRANT': 5, 'SKETCHLEY': 9, 'REUSTLE': 7, 'HUSE': 4, 'MELLGARD': 8}

## Comprehensions with Conditions

In [69]:
marks

[27, 25, 22, 20, 16]

In [70]:
result = ["Excellent" if m > 20 else "Good" for m in marks]
result

['Excellent', 'Excellent', 'Excellent', 'Good', 'Good']

In [71]:
result = ["Excellent" if m > 25 else "V. Good" if m > 20 else "Fail" for m in marks]
result

['Excellent', 'V. Good', 'V. Good', 'Fail', 'Fail']

In [72]:
result = {m : "Excellent" if m > 20 else "Good" for m in marks}
result

{27: 'Excellent', 25: 'Excellent', 22: 'Excellent', 20: 'Good', 16: 'Good'}

In [73]:
result = [m for m in marks if m > 20]
result

[27, 25, 22]

In [75]:
%%timeit
result = {m : "Excellent" if m > 25 else "Good" for m in marks if m > 20}
result

409 ns ± 4.45 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


## `zip` and `enumerate` functions

In [76]:
marks

[27, 25, 22, 20, 16]

In [78]:
names = ["Ahmed", "Ali", "Wael", "Fahad", "Abass"]

In [79]:
result = {n: m for n, m in zip(names, marks)}
result

{'Ahmed': 27, 'Ali': 25, 'Wael': 22, 'Fahad': 20, 'Abass': 16}

In [82]:
result = [(n, m) for n in names for m in marks]
result

[('Ahmed', 27),
 ('Ahmed', 25),
 ('Ahmed', 22),
 ('Ahmed', 20),
 ('Ahmed', 16),
 ('Ali', 27),
 ('Ali', 25),
 ('Ali', 22),
 ('Ali', 20),
 ('Ali', 16),
 ('Wael', 27),
 ('Wael', 25),
 ('Wael', 22),
 ('Wael', 20),
 ('Wael', 16),
 ('Fahad', 27),
 ('Fahad', 25),
 ('Fahad', 22),
 ('Fahad', 20),
 ('Fahad', 16),
 ('Abass', 27),
 ('Abass', 25),
 ('Abass', 22),
 ('Abass', 20),
 ('Abass', 16)]

In [84]:
marks[::-1]

[16, 20, 22, 25, 27]

In [87]:
result = {n: m for n, m in zip(names, marks[::-1])}
result

{'Ahmed': 16, 'Ali': 20, 'Wael': 22, 'Fahad': 25, 'Abass': 27}

In [88]:
names

['Ahmed', 'Ali', 'Wael', 'Fahad', 'Abass']

In [90]:
result = [(i+1, n) for i, n in enumerate(names)]
result

[(1, 'Ahmed'), (2, 'Ali'), (3, 'Wael'), (4, 'Fahad'), (5, 'Abass')]

In [92]:
list(enumerate(zip(names, marks)))

[(0, ('Ahmed', 27)),
 (1, ('Ali', 25)),
 (2, ('Wael', 22)),
 (3, ('Fahad', 20)),
 (4, ('Abass', 16))]

In [93]:
list(zip(names,enumerate(marks)))

[('Ahmed', (0, 27)),
 ('Ali', (1, 25)),
 ('Wael', (2, 22)),
 ('Fahad', (3, 20)),
 ('Abass', (4, 16))]

## Numpy

In [95]:
import numpy as np

marks = np.array([20, 25, 27, 16, 22])
type(marks)

numpy.ndarray

In [100]:
marks - 2

array([18, 23, 25, 14, 20])

In [99]:
marks * 2 - 10

array([30, 40, 44, 22, 34])

In [101]:
marks[0]

20

In [102]:
marks[-1]

22

In [103]:
marks[0:3]

array([20, 25, 27])

In [104]:
marks[marks > 20]

array([25, 27, 22])

In [106]:
mask = marks > 20
marks[mask]

array([25, 27, 22])

In [107]:
mask

array([False,  True,  True, False,  True])

In [108]:
arr_A = np.array(['ostentatious','house','industrial',None,'dog',8,'eat'])
arr_A

array(['ostentatious', 'house', 'industrial', None, 'dog', 8, 'eat'],
      dtype=object)

In [110]:
numbers = np.array([25, 23, 10, 15.8])
numbers

array([25. , 23. , 10. , 15.8])

In [111]:
numbers.dtype

dtype('float64')

In [112]:
numbers = np.array([25, 23, 10, 15.8, "10"])
numbers

array(['25', '23', '10', '15.8', '10'], dtype='<U32')

In [113]:
marks.max()

27

In [114]:
marks.min()

16

In [115]:
marks.sum()

110

In [116]:
np.sum(marks)

110

In [117]:
np.mean(marks)

22.0

In [118]:
marks

array([20, 25, 27, 16, 22])

In [119]:
np.var(marks)

14.8

In [120]:
np.std(marks)

3.847076812334269