# Data Analysis Course
## using Python

In [25]:
print("Welcome to Python")

Welcome to Python


[Our Website](https://www.abadnet.com.sa)

![Logo](https://cdn.dribbble.com/users/10882/screenshots/15172621/media/cd2246d5d0f54f9a4316bd4d276764b2.png?compress=1&resize=400x300)

### Topics:
   - Python Revision
   - Data **Cleaning**
   - Data *Visualization*
   - Models
   
> This is a quote
> 
> more text

## Lists

In [26]:
marks = [23, 18, 12, 25]

In [27]:
marks

[23, 18, 12, 25]

In [28]:
marks[0]

23

In [29]:
marks[-1]

25

In [30]:
len(marks)

4

In [31]:
marks.append(17)
marks

[23, 18, 12, 25, 17]

In [32]:
marks.insert(0, 20)
marks

[20, 23, 18, 12, 25, 17]

In [33]:
marks_g2 = [18, 25, 23, 14]
marks.extend(marks_g2)
marks

[20, 23, 18, 12, 25, 17, 18, 25, 23, 14]

In [34]:
marks += marks_g2
marks

[20, 23, 18, 12, 25, 17, 18, 25, 23, 14, 18, 25, 23, 14]

In [35]:
marks.remove(14)
marks

[20, 23, 18, 12, 25, 17, 18, 25, 23, 18, 25, 23, 14]

In [36]:
marks.pop(5)
marks

[20, 23, 18, 12, 25, 18, 25, 23, 18, 25, 23, 14]

In [37]:
marks.sort(reverse=True)
marks

[25, 25, 25, 23, 23, 23, 20, 18, 18, 18, 14, 12]

In [38]:
marks = list(set(marks))
marks

[12, 14, 18, 20, 23, 25]

In [39]:
# marks[0]

In [40]:
marks.sort(reverse=True)
marks

[25, 23, 20, 18, 14, 12]

In [41]:
marks[0:3]

[25, 23, 20]

In [42]:
marks[:3]

[25, 23, 20]

In [43]:
marks[-3:]

[18, 14, 12]

In [44]:
del marks[-1]

In [45]:
marks

[25, 23, 20, 18, 14]

In [46]:
13 in marks

False

## Tuple:

In [47]:
days = ("Sunday", "Monday", "Tuesday", "Wednesday")
days

('Sunday', 'Monday', 'Tuesday', 'Wednesday')

In [48]:
days[0]

'Sunday'

In [49]:
days[-1]

'Wednesday'

In [50]:
len(days)

4

In [51]:
# days[0] = "Sun"  -- Will not work because tuple is immutable

In [52]:
list(days)

['Sunday', 'Monday', 'Tuesday', 'Wednesday']

## Dict:

In [53]:
countries = {
    "sa": "Saudi Arabia",
    "ae": "Arab Emirates",
    "eg": "Egypt"
}

In [54]:
# countries["ae"]
countries.get("ae", "Not Found")

'Arab Emirates'

In [55]:
countries

{'sa': 'Saudi Arabia', 'ae': 'Arab Emirates', 'eg': 'Egypt'}

In [56]:
list(countries.values())

['Saudi Arabia', 'Arab Emirates', 'Egypt']

In [57]:
list(countries.keys())

['sa', 'ae', 'eg']

In [58]:
items = list(countries.items())
items

[('sa', 'Saudi Arabia'), ('ae', 'Arab Emirates'), ('eg', 'Egypt')]

In [59]:
items[0][1]

'Saudi Arabia'

In [60]:
# countries["eg"] = "Republic of Egypt"
countries.update({"eg": "Republic of Egypt"})
countries

{'sa': 'Saudi Arabia', 'ae': 'Arab Emirates', 'eg': 'Republic of Egypt'}

In [61]:
# countries["pl"] = "Palstine"
countries.update({"pl": "Palstine"})
countries

{'sa': 'Saudi Arabia',
 'ae': 'Arab Emirates',
 'eg': 'Republic of Egypt',
 'pl': 'Palstine'}

In [62]:
# del countries["ae"]
countries.pop("ae")
countries

{'sa': 'Saudi Arabia', 'eg': 'Republic of Egypt', 'pl': 'Palstine'}

In [63]:
len(countries)

3

In [64]:
"ae" in countries

False

In [65]:
list(countries)

['sa', 'eg', 'pl']

In [66]:
list("Welcome")

['W', 'e', 'l', 'c', 'o', 'm', 'e']

## Loops:

for `new_var` in `iterable`:

    >
    >
    
--
--
    

In [67]:
for m in marks:
    print(m + 2)
    print("-" * 20)

print("*" * 20)

27
--------------------
25
--------------------
22
--------------------
20
--------------------
16
--------------------
********************


In [68]:
message = "Hello"
for c in message:
    print(c)
    

H
e
l
l
o


In [69]:
mobile = "0599888921"
for d in mobile:
    if not d.isdigit():
        print("Not a valid mobile")
        break


In [70]:
mobile.isdigit()

True

In [71]:
list(range(1, 10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [72]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [73]:
list(range(1, 10, 2))

[1, 3, 5, 7, 9]

In [74]:
for i in range(10):
    print(i * "-")
#     print("Hello world")



-
--
---
----
-----
------
-------
--------
---------


while `bool-expr`:
    
    --
    --
    
 --

In [75]:
x = 1
while x <= 10:
    print(x)
    x += 1


1
2
3
4
5
6
7
8
9
10


In [76]:
for y in range(1, 11):
    print(y)

1
2
3
4
5
6
7
8
9
10


In [77]:
countries

{'sa': 'Saudi Arabia', 'eg': 'Republic of Egypt', 'pl': 'Palstine'}

In [78]:
for k, v in countries.items():
    print(k, "=>", v)

sa => Saudi Arabia
eg => Republic of Egypt
pl => Palstine


## List & Dict Comprehension

In [79]:
for i in range(len(marks)):
    marks[i] += 2
    
marks

[27, 25, 22, 20, 16]

In [80]:
new_marks = []
for m in marks:
    new_marks.append(m + 2)
    
new_marks

[29, 27, 24, 22, 18]

In [81]:
marks

[27, 25, 22, 20, 16]

In [82]:
new_marks = [m + 5 for m in marks]
new_marks

[32, 30, 27, 25, 21]

In [83]:

teas = ['earl grey', 'darjeeling', 'english breakfast', 'lapsang souchong', 
        'oolong', 'kombucha', 'green tea']

teas = [t.upper() for t in teas]
teas

['EARL GREY',
 'DARJEELING',
 'ENGLISH BREAKFAST',
 'LAPSANG SOUCHONG',
 'OOLONG',
 'KOMBUCHA',
 'GREEN TEA']

In [84]:
text = "Hello"
text.count("e")

1

In [85]:
lengths = [len(t) for t in teas]
lengths

[9, 10, 17, 16, 6, 8, 9]

In [86]:
countries = ["Saudi Arabia", "Arab Emirates", "Egypt"]
countries_d = {c[0]: c for c in countries}
countries_d

{'S': 'Saudi Arabia', 'A': 'Arab Emirates', 'E': 'Egypt'}

In [87]:
lengths = {t: len(t) for t in teas}
lengths

{'EARL GREY': 9,
 'DARJEELING': 10,
 'ENGLISH BREAKFAST': 17,
 'LAPSANG SOUCHONG': 16,
 'OOLONG': 6,
 'KOMBUCHA': 8,
 'GREEN TEA': 9}

In [88]:
lengths = {t: [len(t), t.count(" ") + 1] for t in teas}
lengths

{'EARL GREY': [9, 2],
 'DARJEELING': [10, 1],
 'ENGLISH BREAKFAST': [17, 2],
 'LAPSANG SOUCHONG': [16, 2],
 'OOLONG': [6, 1],
 'KOMBUCHA': [8, 1],
 'GREEN TEA': [9, 2]}

In [89]:
lengths = {t: (len(t), t.count(" ") + 1) for t in teas}
lengths

{'EARL GREY': (9, 2),
 'DARJEELING': (10, 1),
 'ENGLISH BREAKFAST': (17, 2),
 'LAPSANG SOUCHONG': (16, 2),
 'OOLONG': (6, 1),
 'KOMBUCHA': (8, 1),
 'GREEN TEA': (9, 2)}

In [90]:
print(lengths["EARL GREY"][1])

2


In [91]:
print(lengths["EARL GREY"])

(9, 2)


In [92]:
surnames = ['grant','Sketchley','REUSTLE','huse','Mellgard']

result = {n.upper(): len(n) for n in surnames}
result

{'GRANT': 5, 'SKETCHLEY': 9, 'REUSTLE': 7, 'HUSE': 4, 'MELLGARD': 8}

## Comprehensions with Conditions

In [93]:
marks

[27, 25, 22, 20, 16]

In [94]:
result = ["Excellent" if m > 20 else "Good" for m in marks]
result

['Excellent', 'Excellent', 'Excellent', 'Good', 'Good']

In [95]:
result = ["Excellent" if m > 25 else "V. Good" if m > 20 else "Fail" for m in marks]
result

['Excellent', 'V. Good', 'V. Good', 'Fail', 'Fail']

In [96]:
result = {m : "Excellent" if m > 20 else "Good" for m in marks}
result

{27: 'Excellent', 25: 'Excellent', 22: 'Excellent', 20: 'Good', 16: 'Good'}

In [97]:
result = [m for m in marks if m > 20]
result

[27, 25, 22]

In [98]:
%%timeit
result = {m : "Excellent" if m > 25 else "Good" for m in marks if m > 20}
result

418 ns ± 15.7 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


## `zip` and `enumerate` functions

In [99]:
marks

[27, 25, 22, 20, 16]

In [100]:
names = ["Ahmed", "Ali", "Wael", "Fahad", "Abass"]

In [101]:
result = {n: m for n, m in zip(names, marks)}
result

{'Ahmed': 27, 'Ali': 25, 'Wael': 22, 'Fahad': 20, 'Abass': 16}

In [102]:
result = [(n, m) for n in names for m in marks]
result

[('Ahmed', 27),
 ('Ahmed', 25),
 ('Ahmed', 22),
 ('Ahmed', 20),
 ('Ahmed', 16),
 ('Ali', 27),
 ('Ali', 25),
 ('Ali', 22),
 ('Ali', 20),
 ('Ali', 16),
 ('Wael', 27),
 ('Wael', 25),
 ('Wael', 22),
 ('Wael', 20),
 ('Wael', 16),
 ('Fahad', 27),
 ('Fahad', 25),
 ('Fahad', 22),
 ('Fahad', 20),
 ('Fahad', 16),
 ('Abass', 27),
 ('Abass', 25),
 ('Abass', 22),
 ('Abass', 20),
 ('Abass', 16)]

In [103]:
marks[::-1]

[16, 20, 22, 25, 27]

In [104]:
result = {n: m for n, m in zip(names, marks[::-1])}
result

{'Ahmed': 16, 'Ali': 20, 'Wael': 22, 'Fahad': 25, 'Abass': 27}

In [105]:
names

['Ahmed', 'Ali', 'Wael', 'Fahad', 'Abass']

In [106]:
result = [(i+1, n) for i, n in enumerate(names)]
result

[(1, 'Ahmed'), (2, 'Ali'), (3, 'Wael'), (4, 'Fahad'), (5, 'Abass')]

In [107]:
list(enumerate(zip(names, marks)))

[(0, ('Ahmed', 27)),
 (1, ('Ali', 25)),
 (2, ('Wael', 22)),
 (3, ('Fahad', 20)),
 (4, ('Abass', 16))]

In [108]:
list(zip(names,enumerate(marks)))

[('Ahmed', (0, 27)),
 ('Ali', (1, 25)),
 ('Wael', (2, 22)),
 ('Fahad', (3, 20)),
 ('Abass', (4, 16))]

## Numpy

In [109]:
import numpy as np

marks = np.array([20, 25, 27, 16, 22])
type(marks)

numpy.ndarray

In [110]:
marks - 2

array([18, 23, 25, 14, 20])

In [111]:
marks * 2 - 10

array([30, 40, 44, 22, 34])

In [112]:
marks[0]

20

In [113]:
marks[-1]

22

In [114]:
marks[0:3]

array([20, 25, 27])

In [115]:
marks[marks > 20]

array([25, 27, 22])

In [116]:
mask = marks > 20
marks[mask]

array([25, 27, 22])

In [117]:
mask

array([False,  True,  True, False,  True])

In [118]:
arr_A = np.array(['ostentatious','house','industrial',None,'dog',8,'eat'])
arr_A

array(['ostentatious', 'house', 'industrial', None, 'dog', 8, 'eat'],
      dtype=object)

In [119]:
numbers = np.array([25, 23, 10, 15.8])
numbers

array([25. , 23. , 10. , 15.8])

In [120]:
numbers.dtype

dtype('float64')

In [121]:
numbers = np.array([25, 23, 10, 15.8, "10"])
numbers

array(['25', '23', '10', '15.8', '10'], dtype='<U32')

In [122]:
marks.max()

27

In [123]:
marks.min()

16

In [124]:
marks.sum()

110

In [125]:
np.sum(marks)

110

In [126]:
np.mean(marks)

22.0

In [127]:
marks

array([20, 25, 27, 16, 22])

In [128]:
np.var(marks)

14.8

In [129]:
np.std(marks)

3.847076812334269

## Pandas

In [130]:
import pandas as pd

marks = pd.Series([23, 12, 19, 25, 20])
marks

0    23
1    12
2    19
3    25
4    20
dtype: int64

In [131]:
marks[0]

23

In [132]:
marks[0:3]

0    23
1    12
2    19
dtype: int64

In [133]:
mask = marks > 20
marks[mask]

0    23
3    25
dtype: int64

In [134]:
marks + 2

0    25
1    14
2    21
3    27
4    22
dtype: int64

In [135]:
marks = pd.Series([23, 12, 19, 25, 20], index=["Ahmed", "Wael", "Ali", "Nasser", "Abdullah"])
marks

Ahmed       23
Wael        12
Ali         19
Nasser      25
Abdullah    20
dtype: int64

In [136]:
marks["Ahmed"]

23

In [137]:
marks[0]

23

In [138]:
marks["Ahmed":"Ali"]

Ahmed    23
Wael     12
Ali      19
dtype: int64

In [139]:
marks[0:3]

Ahmed    23
Wael     12
Ali      19
dtype: int64

In [140]:
marks.mean()

19.8

In [141]:
marks.median()

20.0

In [142]:
marks.mode()

0    12
1    19
2    20
3    23
4    25
dtype: int64

In [143]:
marks.describe()

count     5.000000
mean     19.800000
std       4.969909
min      12.000000
25%      19.000000
50%      20.000000
75%      23.000000
max      25.000000
dtype: float64

In [144]:
marks = marks.append(pd.Series([15, 5, 26], index=["Abass", "Zaid", "Obaid"]))

In [145]:
marks

Ahmed       23
Wael        12
Ali         19
Nasser      25
Abdullah    20
Abass       15
Zaid         5
Obaid       26
dtype: int64

In [146]:
marks.head(3)

Ahmed    23
Wael     12
Ali      19
dtype: int64

In [147]:
marks.tail(3)

Abass    15
Zaid      5
Obaid    26
dtype: int64

In [148]:
np.random.randint(0, 25, 10)

array([ 2, 13,  1,  4,  7, 21,  2, 17, 24, 13])

In [151]:
np.random.random(10) * 36

array([21.74672441, 12.54358384, 25.7888078 , 23.62494929, 19.92286273,
        1.30688394,  7.58252328,  1.39771122, 32.56005892,  0.4880168 ])

In [152]:
marks

Ahmed       23
Wael        12
Ali         19
Nasser      25
Abdullah    20
Abass       15
Zaid         5
Obaid       26
dtype: int64

In [154]:
mask = marks > 20
marks[mask]

Ahmed     23
Nasser    25
Obaid     26
dtype: int64

In [155]:
mask = (marks >= 15) & (marks <= 20)
marks[mask]

Ali         19
Abdullah    20
Abass       15
dtype: int64

In [156]:
mask = (marks >= 20) | (marks <= 10)
marks[mask]

Ahmed       23
Nasser      25
Abdullah    20
Zaid         5
Obaid       26
dtype: int64

In [157]:
mask = ~(marks > 20)
marks[mask]

Wael        12
Ali         19
Abdullah    20
Abass       15
Zaid         5
dtype: int64

## Pandas DataFrame

In [161]:
data = pd.read_csv("week2/day2/sales.csv", encoding="utf-8")
data

Account                          Name            Rep        Manager  \
0    714466               Trantow-Barrows   Craig Booker   Debra Henley   
1    714466               Trantow-Barrows   Craig Booker   Debra Henley   
2    714466               Trantow-Barrows   Craig Booker   Debra Henley   
3    737550  Fritsch, Russel and Anderson   Craig Booker   Debra Henley   
4    146832                  Kiehn-Spinka  Daniel Hilton   Debra Henley   
5    218895                     Kulas Inc  Daniel Hilton   Debra Henley   
6    218895                     Kulas Inc  Daniel Hilton   Debra Henley   
7    412290                 Jerde-Hilpert     John Smith   Debra Henley   
8    740150                    Barton LLC     John Smith   Debra Henley   
9    141962                    Herman LLC    Cedric Moss  Fred Anderson   
10   163416                   Purdy-Kunde    Cedric Moss  Fred Anderson   
11   239344                    Stokes LLC    Cedric Moss  Fred Anderson   
12   239344                    Stokes LLC    Cedric Moss  Fred Anderson   
13   307599   Kassulke, Ondricka and Metz     Wendy Yule  Fred Anderson   
14   688981                   Keeling LLC     Wendy Yule  Fred Anderson   
15   729833                     Koepp Ltd     Wendy Yule  Fred Anderson   
16   729833                     Koepp Ltd     Wendy Yule  Fred Anderson   
17   123456                        cosmos           neil           lucy   

        Product  Quantity      Price     Status  
0           CPU         1      30000  presented  
1      Software         1      10000  presented  
2   Maintenance         2       5000    pending  
3           CPU         1      35000   declined  
4           CPU         2      65000        won  
5           CPU         2      40000    pending  
6      Software         1      10000  presented  
7   Maintenance         2       5000    pending  
8           CPU         1      35000   declined  
9           CPU         2      65000        won  
10          CPU         1      30000  presented  
11  Maintenance         1       5000    pending  
12     Software         1      10000  presented  
13  Maintenance         3       7000        won  
14          CPU         5     100000        won  
15          CPU         2      65000   declined  
16      Monitor         2       5000  presented  
17     universe         1  1,000,000  presented

In [162]:
type(data)

pandas.core.frame.DataFrame

In [163]:
data.head()

Account                          Name            Rep       Manager  \
0   714466               Trantow-Barrows   Craig Booker  Debra Henley   
1   714466               Trantow-Barrows   Craig Booker  Debra Henley   
2   714466               Trantow-Barrows   Craig Booker  Debra Henley   
3   737550  Fritsch, Russel and Anderson   Craig Booker  Debra Henley   
4   146832                  Kiehn-Spinka  Daniel Hilton  Debra Henley   

       Product  Quantity  Price     Status  
0          CPU         1  30000  presented  
1     Software         1  10000  presented  
2  Maintenance         2   5000    pending  
3          CPU         1  35000   declined  
4          CPU         2  65000        won

In [164]:
data.tail()

Account                         Name         Rep        Manager  \
13   307599  Kassulke, Ondricka and Metz  Wendy Yule  Fred Anderson   
14   688981                  Keeling LLC  Wendy Yule  Fred Anderson   
15   729833                    Koepp Ltd  Wendy Yule  Fred Anderson   
16   729833                    Koepp Ltd  Wendy Yule  Fred Anderson   
17   123456                       cosmos        neil           lucy   

        Product  Quantity      Price     Status  
13  Maintenance         3       7000        won  
14          CPU         5     100000        won  
15          CPU         2      65000   declined  
16      Monitor         2       5000  presented  
17     universe         1  1,000,000  presented

In [165]:
data.sample(5)

Account                          Name           Rep        Manager  \
11   239344                    Stokes LLC   Cedric Moss  Fred Anderson   
9    141962                    Herman LLC   Cedric Moss  Fred Anderson   
3    737550  Fritsch, Russel and Anderson  Craig Booker   Debra Henley   
2    714466               Trantow-Barrows  Craig Booker   Debra Henley   
1    714466               Trantow-Barrows  Craig Booker   Debra Henley   

        Product  Quantity  Price     Status  
11  Maintenance         1   5000    pending  
9           CPU         2  65000        won  
3           CPU         1  35000   declined  
2   Maintenance         2   5000    pending  
1      Software         1  10000  presented

In [166]:
data["Name"]

0                  Trantow-Barrows
1                  Trantow-Barrows
2                  Trantow-Barrows
3     Fritsch, Russel and Anderson
4                     Kiehn-Spinka
5                        Kulas Inc
6                        Kulas Inc
7                    Jerde-Hilpert
8                       Barton LLC
9                       Herman LLC
10                     Purdy-Kunde
11                      Stokes LLC
12                      Stokes LLC
13     Kassulke, Ondricka and Metz
14                     Keeling LLC
15                       Koepp Ltd
16                       Koepp Ltd
17                          cosmos
Name: Name, dtype: object

In [169]:
data[["Name", "Price", "Quantity"]]

Name      Price  Quantity
0                Trantow-Barrows      30000         1
1                Trantow-Barrows      10000         1
2                Trantow-Barrows       5000         2
3   Fritsch, Russel and Anderson      35000         1
4                   Kiehn-Spinka      65000         2
5                      Kulas Inc      40000         2
6                      Kulas Inc      10000         1
7                  Jerde-Hilpert       5000         2
8                     Barton LLC      35000         1
9                     Herman LLC      65000         2
10                   Purdy-Kunde      30000         1
11                    Stokes LLC       5000         1
12                    Stokes LLC      10000         1
13   Kassulke, Ondricka and Metz       7000         3
14                   Keeling LLC     100000         5
15                     Koepp Ltd      65000         2
16                     Koepp Ltd       5000         2
17                        cosmos  1,000,000         1

In [171]:
data[5:10]

Account           Name            Rep        Manager      Product  \
5   218895      Kulas Inc  Daniel Hilton   Debra Henley          CPU   
6   218895      Kulas Inc  Daniel Hilton   Debra Henley     Software   
7   412290  Jerde-Hilpert     John Smith   Debra Henley  Maintenance   
8   740150     Barton LLC     John Smith   Debra Henley          CPU   
9   141962     Herman LLC    Cedric Moss  Fred Anderson          CPU   

   Quantity  Price     Status  
5         2  40000    pending  
6         1  10000  presented  
7         2   5000    pending  
8         1  35000   declined  
9         2  65000        won

In [173]:
data.loc[:, :]

Account                          Name            Rep        Manager  \
0    714466               Trantow-Barrows   Craig Booker   Debra Henley   
1    714466               Trantow-Barrows   Craig Booker   Debra Henley   
2    714466               Trantow-Barrows   Craig Booker   Debra Henley   
3    737550  Fritsch, Russel and Anderson   Craig Booker   Debra Henley   
4    146832                  Kiehn-Spinka  Daniel Hilton   Debra Henley   
5    218895                     Kulas Inc  Daniel Hilton   Debra Henley   
6    218895                     Kulas Inc  Daniel Hilton   Debra Henley   
7    412290                 Jerde-Hilpert     John Smith   Debra Henley   
8    740150                    Barton LLC     John Smith   Debra Henley   
9    141962                    Herman LLC    Cedric Moss  Fred Anderson   
10   163416                   Purdy-Kunde    Cedric Moss  Fred Anderson   
11   239344                    Stokes LLC    Cedric Moss  Fred Anderson   
12   239344                    Stokes LLC    Cedric Moss  Fred Anderson   
13   307599   Kassulke, Ondricka and Metz     Wendy Yule  Fred Anderson   
14   688981                   Keeling LLC     Wendy Yule  Fred Anderson   
15   729833                     Koepp Ltd     Wendy Yule  Fred Anderson   
16   729833                     Koepp Ltd     Wendy Yule  Fred Anderson   
17   123456                        cosmos           neil           lucy   

        Product  Quantity      Price     Status  
0           CPU         1      30000  presented  
1      Software         1      10000  presented  
2   Maintenance         2       5000    pending  
3           CPU         1      35000   declined  
4           CPU         2      65000        won  
5           CPU         2      40000    pending  
6      Software         1      10000  presented  
7   Maintenance         2       5000    pending  
8           CPU         1      35000   declined  
9           CPU         2      65000        won  
10          CPU         1      30000  presented  
11  Maintenance         1       5000    pending  
12     Software         1      10000  presented  
13  Maintenance         3       7000        won  
14          CPU         5     100000        won  
15          CPU         2      65000   declined  
16      Monitor         2       5000  presented  
17     universe         1  1,000,000  presented

In [174]:
data.loc[5:10, "Name":"Product"]

Name            Rep        Manager      Product
5       Kulas Inc  Daniel Hilton   Debra Henley          CPU
6       Kulas Inc  Daniel Hilton   Debra Henley     Software
7   Jerde-Hilpert     John Smith   Debra Henley  Maintenance
8      Barton LLC     John Smith   Debra Henley          CPU
9      Herman LLC    Cedric Moss  Fred Anderson          CPU
10    Purdy-Kunde    Cedric Moss  Fred Anderson          CPU

In [176]:
data.iloc[5:10, 1:5]

Name            Rep        Manager      Product
5      Kulas Inc  Daniel Hilton   Debra Henley          CPU
6      Kulas Inc  Daniel Hilton   Debra Henley     Software
7  Jerde-Hilpert     John Smith   Debra Henley  Maintenance
8     Barton LLC     John Smith   Debra Henley          CPU
9     Herman LLC    Cedric Moss  Fred Anderson          CPU

In [178]:
mask = data["Product"] == "CPU"
data[mask]

Account                          Name            Rep        Manager  \
0    714466               Trantow-Barrows   Craig Booker   Debra Henley   
3    737550  Fritsch, Russel and Anderson   Craig Booker   Debra Henley   
4    146832                  Kiehn-Spinka  Daniel Hilton   Debra Henley   
5    218895                     Kulas Inc  Daniel Hilton   Debra Henley   
8    740150                    Barton LLC     John Smith   Debra Henley   
9    141962                    Herman LLC    Cedric Moss  Fred Anderson   
10   163416                   Purdy-Kunde    Cedric Moss  Fred Anderson   
14   688981                   Keeling LLC     Wendy Yule  Fred Anderson   
15   729833                     Koepp Ltd     Wendy Yule  Fred Anderson   

   Product  Quantity   Price     Status  
0      CPU         1   30000  presented  
3      CPU         1   35000   declined  
4      CPU         2   65000        won  
5      CPU         2   40000    pending  
8      CPU         1   35000   declined  
9      CPU         2   65000        won  
10     CPU         1   30000  presented  
14     CPU         5  100000        won  
15     CPU         2   65000   declined

In [181]:
mask = data["Quantity"] > 2
data[mask]

Account                         Name         Rep        Manager  \
13   307599  Kassulke, Ondricka and Metz  Wendy Yule  Fred Anderson   
14   688981                  Keeling LLC  Wendy Yule  Fred Anderson   

        Product  Quantity   Price Status  
13  Maintenance         3    7000    won  
14          CPU         5  100000    won

In [180]:
data.dtypes

Account      int64
Name        object
Rep         object
Manager     object
Product     object
Quantity     int64
Price       object
Status      object
dtype: object

In [182]:
data["Manager"].value_counts()

Debra Henley     9
Fred Anderson    8
lucy             1
Name: Manager, dtype: int64

In [183]:
temp = pd.DataFrame(np.random.randint(0, 10, (4, 6)))
temp

0  1  2  3  4  5
0  4  0  4  8  8  5
1  7  2  9  8  8  9
2  4  7  1  0  0  3
3  6  9  0  1  7  7

In [184]:
temp.max()

0    7
1    9
2    9
3    8
4    8
5    9
dtype: int32

In [185]:
temp.max(axis=1)

0    8
1    9
2    7
3    9
dtype: int32

In [186]:
temp.apply(np.sqrt)

0         1    2         3         4         5
0  2.000000  0.000000  2.0  2.828427  2.828427  2.236068
1  2.645751  1.414214  3.0  2.828427  2.828427  3.000000
2  2.000000  2.645751  1.0  0.000000  0.000000  1.732051
3  2.449490  3.000000  0.0  1.000000  2.645751  2.645751